# Generated by Django 3.2.8 on 2021-12-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_basket_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='is_active',
        ),
    ]
